// <auto-generated />
using System;
using Codwer.Intern.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Codwer.Intern.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211101095132_AddFKinBook")]
    partial class AddFKinBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Codwer.Intern.Persistence.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CoverID")
                        .HasColumnType("int");

                    b.Property<int>("IDCover")
                        .HasColumnType("int");

                    b.Property<int>("IDLanguage")
                        .HasColumnType("int");

                    b.Property<int>("IDPartnerPrice")
                        .HasColumnType("int");

                    b.Property<int?>("LanguageID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerPriceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoverID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("PartnerPriceID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Codwer.Intern.Persistence.Entities.Cover", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeCoveer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Covers");
                });

            modelBuilder.Entity("Codwer.Intern.Persistence.Entities.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("language")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Codwer.Intern.Persistence.Entities.PartnerPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("partner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PartnerPrices");
                });

            modelBuilder.Entity("Codwer.Intern.Persistence.Entities.Book", b =>
                {
                    b.HasOne("Codwer.Intern.Persistence.Entities.Cover", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverID");

                    b.HasOne("Codwer.Intern.Persistence.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID");

                    b.HasOne("Codwer.Intern.Persistence.Entities.PartnerPrice", "PartnerPrice")
                        .WithMany()
                        .HasForeignKey("PartnerPriceID");

                    b.Navigation("Cover");

                    b.Navigation("Language");

                    b.Navigation("PartnerPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
